name: txtreme
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - black
  - bottleneck
  - cartopy
  - cdsapi
  - dask
  - geopandas
  - jupyterlab
  - matplotlib
  - mypy
  - nb_black
  - netcdf4
  - numpy
  - openpyxl
  - pandas
  - pip
  - pylint
  - regionmask
  - scipy
  - seaborn
  - snakemake
  - tqdm
  - xarray
  - pip:
      - matplotlib-label-lines
